# Generated by Django 5.2.3 on 2025-06-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField(max_length=500)),
                ('price', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('LUXURY', 'Luxury'), ('SPORTS', 'Sports'), ('SUV', 'SUV'), ('CONVERTIBLE', 'Convertible')], max_length=20)),
                ('features', models.JSONField(default=list)),
                ('whatsapp_number', models.CharField(default='+1234567890', max_length=20)),
                ('call_number', models.CharField(default='+1234567890', max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
