# Generated by Django 5.2.3 on 2025-06-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_customerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ad_slot', models.CharField(blank=True, help_text='Google AdSense ad slot ID', max_length=50)),
                ('page', models.CharField(default='all', help_text="Page where ad appears, e.g., 'about', 'home', or 'all' for site-wide", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('hours', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
