# Generated by Django 5.2.3 on 2025-06-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_adunit_siteinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
