# Generated by Django 5.2.3 on 2025-06-25 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_image_car_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='carcategory',
            options={'verbose_name_plural': 'Car Categories'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='car',
            name='additional_km_rate',
            field=models.CharField(default='AED 5 – AED 30', help_text='Cost per additional km', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='car',
            name='luggage_capacity',
            field=models.PositiveIntegerField(default=2, help_text='Number of luggage bags'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage_limit',
            field=models.PositiveIntegerField(default=250, help_text='Daily mileage limit in km'),
        ),
        migrations.AddField(
            model_name='car',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='passengers',
            field=models.PositiveIntegerField(default=2, help_text='Number of passengers'),
        ),
        migrations.AddField(
            model_name='car',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=3000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.carcategory'),
        ),
        migrations.AlterField(
            model_name='car',
            name='insurance_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='no_security_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='usdt_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='whatsapp_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
        ),
    ]
